CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL,
                         category VARCHAR(50) NOT NULL,
                         size VARCHAR(20),
                         price DECIMAL(10,2) NOT NULL,
                         stock INT NOT NULL
);

INSERT INTO product (name, category, size, price, stock) VALUES
                                                             ('Camiseta Básica', 'Roupas', 'M', 49.90, 20),
                                                             ('Calça Jeans', 'Roupas', '42', 129.90, 10),
                                                             ('Moletom', 'Roupas', 'G', 159.90, 8);